const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      category: "Shirtd",
      image: "/images/p1.jpg",
      price: 120,
      countInStock:10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim shirt",
      category: "Shirtd",
      image: "/images/p2.jpg",
      price: 220,
      countInStock:20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free shirt",
      category: "Shirtd",
      image: "/images/p3.jpg",
      price: 320,
      countInStock:0,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock:15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 40,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 83,
      countInStock:5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants  ",
      image: "/images/p6.jpg",
      price: 125,
      countInStock:12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
